// examples/angular-app/src/app/app.component.ts
import { Component, Input, OnInit } from '@angular/core';

declare const SampleImport: any;

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent implements OnInit {
  ngOnInit(): void {
    const reactUI = SampleImport({
      dom_id: '#rest-import-ui',
      language: 'en',
      config: {
        id: '1234',
        name: 'From library',
        value: 'Save',
      },
    });
  }
}

// src/App.tsx
import { Stack } from '@mui/material'
import SampleImportService from './core/components/SampleImportService'


export default function App() {
  const config: any = {
    objval:{
      id:"1",
      "name":'From library'
    },
    value:"Save"
  }

  return (
      <Stack className='rest-import-ui'>
        <SampleImportService sampleImportConfig={config} language='en' />
      </Stack>
  )
}
